In [94]:
import numpy as np
from scipy.stats import norm
from scipy.optimize import fmin
import math

import yfinance as yf
import pandas as pd
import pandas_market_calendars as mcal

## Black Scholes Pricing and Implied Volatility

In [196]:
def black_scholes(S, K, t, r, sigma, put_or_call='call'):
    d1 = (math.log(S/K) + (r + sigma**2 / 2) * t)/(sigma * np.sqrt(t))
    d2 = (math.log(S/K) + (r - sigma**2 / 2) * t)/(sigma * np.sqrt(t))
    if put_or_call == 'call':
        return S * norm.cdf(d1) - K * math.e**(-r*t) * norm.cdf(d2)
    elif put_or_call == 'put':
        return K * math.e**(-r*t) * norm.cdf(-d2) - S * norm.cdf(-d1)
    else:
        return None

def black_scholes_df(row, S, r, put_or_call='call'):
    K = row['strike']
    t = row['remainingTradeDate']/365
    sigma = row['calculated_iv']

    return black_scholes(S, K, t, r, sigma, put_or_call)

def implied_volatility(s, option_price, S, K, t, r, put_or_call ='call' ):    
    d1 = (math.log(S/K) + (r + s[0]**2 / 2) * t)/(s[0] * np.sqrt(t))
    d2 = (math.log(S/K) + (r - s[0]**2 / 2) * t)/(s[0] * np.sqrt(t))
    calculated_price = black_scholes(S, K, t, r, s[0], put_or_call)

    print('s : ', s)
    print('calculated_price')
    if put_or_call == 'call':
        of = (S * norm.cdf(d1) - K * math.e**(-r*t) * norm.cdf(d2)) - option_price
        val = of**2    
    elif put_or_call == 'put':
        of = (K * math.e**(-r*t) * norm.cdf(-d2) - S * norm.cdf(-d1)) - option_price
        val = of**2
    print(val)

    return val

def iv_objective(s, option_price, S, K, t, r, put_or_call):
    sigma = abs(s[0])
    calculated_price = black_scholes(S, K, t, r, sigma, put_or_call)
    return (calculated_price - option_price)**2

def implied_volatility_df(row, S, r, put_or_call='call', s0=5):
    # print('row : ', row)
    K = row['strike']
    option_price = row['lastPrice']
    t = row['remainingTradeDate']/365

    result = fmin(iv_objective, [s0], args=(option_price, S, K, t, r, put_or_call), disp=False)

    return abs(result[0])

In [69]:
S = 100
K = 105
t = 0.5
r = 0.05
sigma = 0.2

black_scholes(S, K, t, r, sigma, 'put')

np.float64(6.989220930514911)

In [70]:
# implied_volatility([0.3], price, S, K, t, r, 'call')

In [158]:
# bs_price = 6.989220930514911
# iv = fmin(implied_volatility, [0.3], args=(bs_price, S, K, t, r, 'call'))

In [159]:
print(iv)

[2.05426025]

## Gaterhing Options Data

In [65]:
ticker = yf.Ticker('AAPL')

In [50]:
ticker.fast_info['last_price']

332.2699890136719

In [51]:
df_call = None
df_put = None
for exp in ticker.options:
    opt = ticker.option_chain(exp)
    call = opt.calls
    call['exp'] = exp
    df_call = pd.concat([df_call, call], ignore_index=True)
    put = opt.puts
    put['exp'] = exp
    df_put = pd.concat([df_put, put], ignore_index=True)

In [79]:
black_scholes(S, K, t, r, 1.886719, 'call')

np.float64(87.5317238616764)

In [153]:
S = 332.2699890136719
K = 245
t = 2/365
r = 0.0402
bs_price = 87.66

iv = fmin(implied_volatility, [5], args=(bs_price, S, K, t, r, 'call'))
print('iv : ', iv)

s :  [5.]
calculated_price
136.6299827988437
s :  [5.25]
calculated_price
173.89014688880386
s :  [4.75]
calculated_price
104.82864289622826
s :  [4.5]
calculated_price
78.18777097442052
s :  [4.]
calculated_price
38.976719367079454
s :  [3.5]
calculated_price
15.710140800733708
s :  [2.5]
calculated_price
0.5338845745300392
s :  [1.5]
calculated_price
0.11172091928151029
s :  [-0.5]
calculated_price
7684.275599999999
s :  [2.5]
calculated_price
0.5338845745300392
s :  [0.5]
calculated_price
0.13188746799876996
s :  [1.]
calculated_price
0.1318228521583977
s :  [2.]
calculated_price
0.0033537737566396307
s :  [2.5]
calculated_price
0.5338845745300392
s :  [2.5]
calculated_price
0.5338845745300392
s :  [1.75]
calculated_price
0.06130729971585899
s :  [2.25]
calculated_price
0.06962739405817785
s :  [1.875]
calculated_price
0.02817214901269847
s :  [2.125]
calculated_price
0.007277617405551251
s :  [2.0625]
calculated_price
8.809018075634333e-05
s :  [2.125]
calculated_price
0.007277617405551251
s :  [2.03125]
calculated_price
0.0006413491861674899
s :  [2.09375]
calculated_price
0.002139397046388145
s :  [2.046875]
calculated_price
6.785278003741719e-05
s :  [2.03125]
calculated_price
0.0006413491861674899
s :  [2.0546875]
calculated_price
2.5704956737095126e-07
s :  [2.0625]
calculated_price
8.809018075634333e-05
s :  [2.05078125]
calculated_price
1.5069162844482652e-05
s :  [2.05859375]
calculated_price
2.429989441219132e-05
s :  [2.05273438]
calculated_price
2.8616639494300137e-06
s :  [2.05664062]
calculated_price
7.366033633909631e-06
s :  [2.05371094]
calculated_price
3.520897997180463e-07
s :  [2.05566406]
calculated_price
2.5904001294371594e-06
s :  [2.05419922]
calculated_price
1.8877157045449964e-09
s :  [2.05371094]
calculated_price
3.520897997180463e-07
s :  [2.05444336]
calculated_price
5.3689875485452366e-08
s :  [2.05395508]
calculated_price
1.0142650539010039e-07
s :  [2.05432129]
calculated_price
8.857643725945323e-09
s :  [2.05407715]
calculated_price
3.275302288515217e-08
s :  [2.05426025]
calculated_price
6.415837360820857e-10
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 20
         Function evaluations: 40
iv :  [2.05426025]

In [188]:
cal = mcal.get_calendar('NYSE')
def trading_days(start_date, end_date, cal):
    
    schedule = cal.schedule(start_date, end_date)
    trading_days = mcal.date_range(schedule, frequency='1D').date

    return len(trading_days)

def trading_days_df(row, cal):
    # print('tes')
    # print('row : ', row)
    start_date = row['lastTradeDate']
    # print('start_date : ', start_date)
    end_date = row['exp']
    # print('end_date : ', end_date)
    schedule = cal.schedule(start_date, end_date)
    trading_days = mcal.date_range(schedule, frequency='1D').date

    return len(trading_days)

def trading_days_df_future(row, cal):
    # print('tes')
    # print('row : ', row)
    start_date = row['futureDate']
    # print('start_date : ', start_date)
    end_date = row['exp']
    # print('end_date : ', end_date)
    schedule = cal.schedule(start_date, end_date)
    trading_days = mcal.date_range(schedule, frequency='1D').date

    return len(trading_days)

In [155]:
df_call['lastTradeDate'][0:10]

0   2026-09-11 19:46:47+00:00
1   2026-09-11 15:38:06+00:00
2   2026-09-11 19:54:10+00:00
3   2026-09-11 19:38:49+00:00
4   2026-09-11 19:50:57+00:00
5   2026-09-11 19:58:19+00:00
6   2026-09-11 19:49:10+00:00
7   2026-09-11 19:59:52+00:00
8   2026-09-11 19:59:46+00:00
9   2026-09-11 19:59:43+00:00
Name: lastTradeDate, dtype: datetime64[s, UTC]

In [156]:
trading_days('2026-09-11', '2026-09-14', cal)

2

In [147]:
df_call.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,exp,remainingTradeDate
0,AAPL260914C00245000,2026-09-11 19:46:47+00:00,245.0,87.66,85.75,89.2,9.510002,12.168908,20.0,1,1.886719,True,REGULAR,USD,2026-09-14,2
1,AAPL260914C00285000,2026-09-11 15:38:06+00:00,285.0,50.20,45.80,48.4,4.930000,10.890215,1.0,12,1.449222,True,REGULAR,USD,2026-09-14,2
2,AAPL260914C00290000,2026-09-11 19:54:10+00:00,290.0,42.60,41.50,42.6,12.099998,39.672127,23.0,10,1.018560,True,REGULAR,USD,2026-09-14,2
3,AAPL260914C00295000,2026-09-11 19:38:49+00:00,295.0,37.52,36.10,38.6,7.520001,25.066668,8.0,35,0.726565,True,REGULAR,USD,2026-09-14,2
4,AAPL260914C00300000,2026-09-11 19:50:57+00:00,300.0,32.45,31.15,33.4,7.270001,28.872124,309.0,40,1.062016,True,REGULAR,USD,2026-09-14,2

In [138]:
df_call['remainingTradeDate'] = df_call.apply(trading_days_df, axis=1, cal=cal)

In [142]:
df_put['remainingTradeDate'] = df_put.apply(trading_days_df, axis=1, cal=cal)

In [165]:
df_call.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,exp,remainingTradeDate
0,AAPL260914C00245000,2026-09-11 19:46:47+00:00,245.0,87.66,85.75,89.2,9.510002,12.168908,20.0,1,1.886719,True,REGULAR,USD,2026-09-14,2
1,AAPL260914C00285000,2026-09-11 15:38:06+00:00,285.0,50.20,45.80,48.4,4.930000,10.890215,1.0,12,1.449222,True,REGULAR,USD,2026-09-14,2
2,AAPL260914C00290000,2026-09-11 19:54:10+00:00,290.0,42.60,41.50,42.6,12.099998,39.672127,23.0,10,1.018560,True,REGULAR,USD,2026-09-14,2
3,AAPL260914C00295000,2026-09-11 19:38:49+00:00,295.0,37.52,36.10,38.6,7.520001,25.066668,8.0,35,0.726565,True,REGULAR,USD,2026-09-14,2
4,AAPL260914C00300000,2026-09-11 19:50:57+00:00,300.0,32.45,31.15,33.4,7.270001,28.872124,309.0,40,1.062016,True,REGULAR,USD,2026-09-14,2

In [168]:
df_call['strike']

0       245.0
1       285.0
2       290.0
3       295.0
4       300.0
        ...
1303    560.0
1304    570.0
1305    580.0
1306    590.0
1307    600.0
Name: strike, Length: 1308, dtype: float64

In [182]:
df_call['calculated_iv'] = df_call.apply(implied_volatility_df, axis=1, S=S, r=r, put_or_call='call')
df_put['calculated_iv'] = df_put.apply(implied_volatility_df, axis=1, S=S, r=r, put_or_call='put')

/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/795459077.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  d1 = (math.log(S/K) + (r + sigma**2 / 2) * t)/(sigma * np.sqrt(t))
/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/795459077.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  d2 = (math.log(S/K) + (r - sigma**2 / 2) * t)/(sigma * np.sqrt(t))
/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/795459077.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  d1 = (math.log(S/K) + (r + sigma**2 / 2) * t)/(sigma * np.sqrt(t))
/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/795459077.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  d2 = (math.log(S/K) + (r - sigma**2 / 2) * t)/(sigma * np.sqrt(t))

In [187]:
df_call[10:20]

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,exp,remainingTradeDate,calculated_iv
10,AAPL260914C00330000,2026-09-11 19:59:58+00:00,330.0,3.40,3.30,3.55,1.49,78.010480,18399.0,5843,0.228523,True,REGULAR,USD,2026-09-14,2,0.208984
11,AAPL260914C00335000,2026-09-11 19:59:59+00:00,335.0,1.02,0.98,1.05,0.25,32.467533,61462.0,2911,0.217537,False,REGULAR,USD,2026-09-14,2,0.212891
12,AAPL260914C00340000,2026-09-11 19:59:59+00:00,340.0,0.20,0.20,0.24,-0.10,-33.333336,26076.0,2511,0.231453,False,REGULAR,USD,2026-09-14,2,0.220459
13,AAPL260914C00345000,2026-09-11 19:59:58+00:00,345.0,0.06,0.05,0.06,-0.06,-50.000000,9379.0,714,0.257820,False,REGULAR,USD,2026-09-14,2,0.257568
14,AAPL260914C00350000,2026-09-11 19:59:58+00:00,350.0,0.02,0.02,0.03,-0.02,-50.000000,5375.0,1760,0.308601,False,REGULAR,USD,2026-09-14,2,0.291931
15,AAPL260914C00355000,2026-09-11 19:56:17+00:00,355.0,0.01,0.00,0.02,-0.01,-50.000000,961.0,272,0.359381,False,REGULAR,USD,2026-09-14,2,0.334473
16,AAPL260914C00360000,2026-09-11 19:20:01+00:00,360.0,0.02,0.00,0.02,0.00,0.000000,684.0,496,0.429693,False,REGULAR,USD,2026-09-14,2,0.427490
17,AAPL260914C00365000,2026-09-11 13:43:27+00:00,365.0,0.01,0.00,0.04,-0.02,-66.666670,40.0,88,0.535161,False,REGULAR,USD,2026-09-14,2,0.458008
18,AAPL260914C00370000,2026-09-11 14:48:22+00:00,370.0,0.01,0.00,0.14,0.00,0.000000,15.0,277,0.644535,False,REGULAR,USD,2026-09-14,2,0.517212
19,AAPL260914C00375000,2026-09-11 14:41:42+00:00,375.0,0.01,0.00,0.04,0.00,0.000000,4.0,14,0.617191,False,REGULAR,USD,2026-09-14,2,0.575012

In [186]:
df_put.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,exp,remainingTradeDate,calculated_iv
0,AAPL260914P00250000,2026-09-11 13:36:13+00:00,250.0,0.01,0.0,0.06,0.00,0.0,9501.0,3,1.414065,False,REGULAR,USD,2026-09-14,2,1.276855
1,AAPL260914P00255000,2026-09-11 13:36:33+00:00,255.0,0.01,0.0,0.01,0.00,0.0,10500.0,373,1.125004,False,REGULAR,USD,2026-09-14,2,1.194397
2,AAPL260914P00260000,2026-09-11 17:20:15+00:00,260.0,0.01,0.0,0.02,0.00,0.0,1.0,369,1.109379,False,REGULAR,USD,2026-09-14,2,1.113159
3,AAPL260914P00265000,2026-09-11 19:47:43+00:00,265.0,0.01,0.0,0.01,0.00,0.0,5.0,161,0.968750,False,REGULAR,USD,2026-09-14,2,1.033203
4,AAPL260914P00270000,2026-09-11 19:47:43+00:00,270.0,0.03,0.0,0.05,0.01,50.0,2.0,33,1.039067,False,REGULAR,USD,2026-09-14,2,1.061340

In [192]:
df_call_future

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,exp,remainingTradeDate,calculated_iv,futureDate
0,AAPL261016C00130000,2026-09-09 15:11:58+00:00,130.0,185.00,200.90,204.80,0.00,0.000000,1.0,34,1.460452,True,REGULAR,USD,2026-10-16,28,0.000000,2026-10-10
1,AAPL261016C00135000,2026-09-01 14:53:41+00:00,135.0,190.63,196.35,199.85,0.00,0.000000,1.0,61,1.485842,True,REGULAR,USD,2026-10-16,33,0.000000,2026-10-10
2,AAPL261016C00140000,2026-09-01 18:37:22+00:00,140.0,186.05,191.30,194.85,0.00,0.000000,2.0,24,1.423831,True,REGULAR,USD,2026-10-16,33,0.000000,2026-10-10
3,AAPL261016C00145000,2026-08-04 14:21:00+00:00,145.0,162.99,174.30,177.65,0.00,0.000000,9.0,18,0.000010,True,REGULAR,USD,2026-10-16,53,0.000000,2026-10-10
4,AAPL261016C00150000,2026-09-01 15:13:09+00:00,150.0,173.50,181.30,184.90,0.00,0.000000,1.0,18,1.326175,True,REGULAR,USD,2026-10-16,33,0.000000,2026-10-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030,AAPL281215C00560000,2026-09-10 15:03:29+00:00,560.0,11.91,12.75,14.00,0.00,0.000000,1.0,94,0.317084,False,REGULAR,USD,2028-12-15,572,0.348450,2026-10-10
1031,AAPL281215C00570000,2026-09-11 14:45:44+00:00,570.0,13.35,11.95,13.00,3.05,29.611652,1.0,48,0.316199,False,REGULAR,USD,2028-12-15,571,0.369507,2026-10-10
1032,AAPL281215C00580000,2026-09-11 19:46:52+00:00,580.0,11.97,11.15,12.35,1.67,16.213593,10.0,153,0.317527,False,REGULAR,USD,2028-12-15,571,0.364685,2026-10-10
1033,AAPL281215C00590000,2026-09-11 13:45:32+00:00,590.0,11.09,10.15,11.70,1.53,16.004180,11.0,205,0.318504,False,REGULAR,USD,2028-12-15,571,0.363770,2026-10-10
1034,AAPL281215C00600000,2026-09-11 19:27:34+00:00,600.0,10.21,9.80,10.40,1.06,11.584704,141.0,4706,0.313743,False,REGULAR,USD,2028-12-15,571,0.362244,2026-10-10

In [205]:
S

332.2699890136719

## Future Option Price

In [198]:
future_S = 400
r = 0.0402

future_date = '2026-10-10'

df_call_future = df_call[df_call['exp'] > future_date].reset_index(drop=True)
df_put_future = df_put[df_put['exp'] > future_date].reset_index(drop=True)

df_call_future['futureDate'] = future_date
df_put_future['futureDate'] = future_date

df_call_future['remainingTradeDate'] = df_call_future.apply(trading_days_df_future, axis=1, cal=cal)
df_put_future['remainingTradeDate'] = df_put_future.apply(trading_days_df_future, axis=1, cal=cal)

In [200]:
df_call_future['future_option_price'] = df_call_future.apply(black_scholes_df, axis=1, S=future_S, r=r, put_or_call='call')

/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/2013982487.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  d1 = (math.log(S/K) + (r + sigma**2 / 2) * t)/(sigma * np.sqrt(t))
/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/2013982487.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  d2 = (math.log(S/K) + (r - sigma**2 / 2) * t)/(sigma * np.sqrt(t))

In [202]:
df_put_future['future_option_price'] = df_put_future.apply(black_scholes_df, axis=1, S=future_S, r=r, put_or_call='put')

/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/2013982487.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  d1 = (math.log(S/K) + (r + sigma**2 / 2) * t)/(sigma * np.sqrt(t))
/var/folders/fq/4g0b7nkd5v1d0krt8k9z5_ww0000gn/T/ipykernel_915/2013982487.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  d2 = (math.log(S/K) + (r - sigma**2 / 2) * t)/(sigma * np.sqrt(t))

In [203]:
df_call_future['price_return'] = ((df_call_future['future_option_price'] /  df_call_future['lastPrice']) - 1) * 100
df_put_future['price_return'] = ((df_put_future['future_option_price'] /  df_put_future['lastPrice']) - 1) * 100

In [207]:
df_call_future.head(50)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,exp,remainingTradeDate,calculated_iv,futureDate,future_option_price,price_return
0,AAPL261016C00130000,2026-09-09 15:11:58+00:00,130.0,185.00,200.90,204.80,0.000000,0.000000,1.0,34,1.460452,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,270.071569,45.984632
1,AAPL261016C00135000,2026-09-01 14:53:41+00:00,135.0,190.63,196.35,199.85,0.000000,0.000000,1.0,61,1.485842,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,265.074322,39.051735
2,AAPL261016C00140000,2026-09-01 18:37:22+00:00,140.0,186.05,191.30,194.85,0.000000,0.000000,2.0,24,1.423831,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,260.077075,39.788807
3,AAPL261016C00145000,2026-08-04 14:21:00+00:00,145.0,162.99,174.30,177.65,0.000000,0.000000,9.0,18,0.000010,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,255.079827,56.500293
4,AAPL261016C00150000,2026-09-01 15:13:09+00:00,150.0,173.50,181.30,184.90,0.000000,0.000000,1.0,18,1.326175,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,250.082580,44.139816
5,AAPL261016C00155000,2026-08-28 17:36:20+00:00,155.0,165.77,176.40,179.85,0.000000,0.000000,2.0,62,1.282718,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,245.085333,47.846614
6,AAPL261016C00160000,2026-09-09 15:00:54+00:00,160.0,154.20,171.45,174.85,0.000000,0.000000,1.0,232,1.240238,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,240.088085,55.699147
7,AAPL261016C00165000,2026-09-11 15:52:43+00:00,165.0,170.40,166.40,169.90,18.699997,12.326960,1.0,81,1.193363,True,REGULAR,USD,2026-10-16,5,1.719788,2026-10-10,235.090895,37.964141
8,AAPL261016C00170000,2026-09-08 19:55:28+00:00,170.0,147.03,161.45,164.90,0.000000,0.000000,3.0,63,1.153080,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,230.093591,56.494315
9,AAPL261016C00175000,2026-08-07 14:29:26+00:00,175.0,139.72,156.45,159.95,0.000000,0.000000,2.0,25,1.113774,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,225.096343,61.105313
10,AAPL261016C00180000,2026-09-01 18:22:43+00:00,180.0,146.09,151.50,155.00,0.000000,0.000000,1.0,97,1.080083,True,REGULAR,USD,2026-10-16,5,0.250000,2026-10-10,220.099096,50.659933
11,AAPL261016C00185000,2026-08-20 19:28:29+00:00,185.0,130.39,146.45,150.05,0.000000,0.000000,6.0,34,1.037114,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,215.101849,64.968056
12,AAPL261016C00190000,2026-08-25 16:45:33+00:00,190.0,120.98,141.55,145.00,0.000000,0.000000,1.0,55,1.000005,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,210.104601,73.668872
13,AAPL261016C00195000,2026-09-03 19:15:05+00:00,195.0,133.35,136.60,140.05,0.000000,0.000000,2.0,215,0.967774,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,205.107354,53.811289
14,AAPL261016C00200000,2026-09-11 16:29:11+00:00,200.0,135.00,131.60,135.05,8.800003,6.973061,20.0,299,0.927735,True,REGULAR,USD,2026-10-16,5,1.261169,2026-10-10,200.110117,48.229717
15,AAPL261016C00205000,2026-09-11 15:16:20+00:00,205.0,131.60,126.70,130.10,19.470009,17.363783,4.0,863,0.899903,True,REGULAR,USD,2026-10-16,5,1.367065,2026-10-10,195.113003,48.262161
16,AAPL261016C00210000,2026-08-31 14:20:24+00:00,210.0,107.32,121.60,125.15,0.000000,0.000000,1.0,471,0.857667,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,190.115612,77.148353
17,AAPL261016C00215000,2026-09-11 19:42:41+00:00,215.0,118.00,116.70,120.00,5.949997,5.310126,15.0,478,0.816408,True,REGULAR,USD,2026-10-16,5,0.799316,2026-10-10,185.118365,56.879970
18,AAPL261016C00220000,2026-09-11 15:28:46+00:00,220.0,116.05,111.70,115.15,9.300003,8.711946,1.0,872,0.789553,True,REGULAR,USD,2026-10-16,5,1.157715,2026-10-10,180.121159,55.209961
19,AAPL261016C00225000,2026-09-09 16:23:09+00:00,225.0,89.12,106.80,110.25,0.000000,0.000000,2.0,283,0.765383,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,175.123870,96.503445
20,AAPL261016C00230000,2026-09-11 14:57:40+00:00,230.0,106.00,101.85,105.30,11.129997,11.731841,10.0,593,0.734866,True,REGULAR,USD,2026-10-16,5,1.052612,2026-10-10,170.126649,60.496839
21,AAPL261016C00235000,2026-09-08 18:48:58+00:00,235.0,81.30,96.80,100.25,0.000000,0.000000,28.0,280,0.693118,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,165.129375,103.111163
22,AAPL261016C00240000,2026-09-11 19:57:01+00:00,240.0,93.55,91.85,95.35,8.410004,9.877852,2.0,569,0.666019,True,REGULAR,USD,2026-10-16,5,0.712891,2026-10-10,160.132128,71.172772
23,AAPL261016C00245000,2026-09-09 18:14:56+00:00,245.0,67.71,86.85,90.40,0.000000,0.000000,4.0,314,0.633549,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,155.134881,129.116645
24,AAPL261016C00250000,2026-09-11 19:57:19+00:00,250.0,83.66,82.30,85.15,6.860001,8.932293,165.0,1396,0.608402,True,REGULAR,USD,2026-10-16,5,0.650146,2026-10-10,150.137633,79.461670
25,AAPL261016C00255000,2026-09-11 19:58:33+00:00,255.0,78.78,77.15,80.40,5.930000,8.140014,94.0,1010,0.578373,True,REGULAR,USD,2026-10-16,5,0.626099,2026-10-10,145.140386,84.235067
26,AAPL261016C00260000,2026-09-11 19:52:14+00:00,260.0,73.63,72.05,75.45,6.829994,10.224542,23.0,1526,0.541997,True,REGULAR,USD,2026-10-16,5,0.570618,2026-10-10,140.143139,90.334291
27,AAPL261016C00265000,2026-09-11 17:04:11+00:00,265.0,70.56,67.15,70.55,8.379997,13.476997,4.0,904,0.516118,True,REGULAR,USD,2026-10-16,5,0.695251,2026-10-10,135.145892,91.533294
28,AAPL261016C00270000,2026-09-11 19:48:20+00:00,270.0,64.25,62.20,65.65,6.950001,12.129147,11.0,1429,0.592900,True,REGULAR,USD,2026-10-16,5,0.555908,2026-10-10,130.148644,102.565983
29,AAPL261016C00275000,2026-09-11 15:56:37+00:00,275.0,60.39,57.75,59.60,8.090000,15.468452,16.0,1494,0.496953,True,REGULAR,USD,2026-10-16,5,0.597839,2026-10-10,125.151397,107.238610
30,AAPL261016C00280000,2026-09-11 19:59:18+00:00,280.0,54.14,53.15,55.45,5.939999,12.323648,84.0,2268,0.506231,True,REGULAR,USD,2026-10-16,5,0.469604,2026-10-10,120.154149,121.932304
31,AAPL261016C00285000,2026-09-11 19:45:37+00:00,285.0,49.89,47.75,50.00,7.570000,17.887524,35.0,1829,0.446478,True,REGULAR,USD,2026-10-16,5,0.483032,2026-10-10,115.156902,130.821612
32,AAPL261016C00290000,2026-09-11 19:40:20+00:00,290.0,44.48,43.00,44.85,5.649998,14.550598,188.0,3638,0.402716,True,REGULAR,USD,2026-10-16,5,0.416931,2026-10-10,110.159655,147.661094
33,AAPL261016C00295000,2026-09-11 19:41:19+00:00,295.0,39.88,39.05,39.90,6.220001,18.478910,46.0,2024,0.368781,True,REGULAR,USD,2026-10-16,5,0.401306,2026-10-10,105.162407,163.697110
34,AAPL261016C00300000,2026-09-11 19:59:57+00:00,300.0,34.78,34.60,35.00,4.779999,15.933329,800.0,15655,0.336554,True,REGULAR,USD,2026-10-16,5,0.355347,2026-10-10,100.165160,187.996435
35,AAPL261016C00305000,2026-09-11 19:59:36+00:00,305.0,30.27,30.15,30.55,4.650000,18.149881,118.0,6638,0.320869,True,REGULAR,USD,2026-10-16,5,0.338623,2026-10-10,95.167913,214.396804
36,AAPL261016C00310000,2026-09-11 19:59:37+00:00,310.0,26.05,25.85,26.25,4.379999,20.212273,398.0,10358,0.305976,True,REGULAR,USD,2026-10-16,5,0.328735,2026-10-10,90.170665,246.144589
37,AAPL261016C00315000,2026-09-11 19:59:04+00:00,315.0,22.16,21.80,22.25,3.940001,21.624592,947.0,10396,0.295295,True,REGULAR,USD,2026-10-16,5,0.323364,2026-10-10,85.173418,284.356579
38,AAPL261016C00320000,2026-09-11 19:59:32+00:00,320.0,18.11,18.05,18.40,3.210001,21.543630,2051.0,11896,0.282417,True,REGULAR,USD,2026-10-16,5,0.304077,2026-10-10,80.176171,342.717673
39,AAPL261016C00325000,2026-09-11 19:52:33+00:00,325.0,14.92,14.65,15.10,2.920000,24.333334,3494.0,10261,0.277168,True,REGULAR,USD,2026-10-16,5,0.303467,2026-10-10,75.178923,403.880183
40,AAPL261016C00330000,2026-09-11 19:59:30+00:00,330.0,11.80,11.65,12.00,2.350000,24.867730,5446.0,15785,0.268562,True,REGULAR,USD,2026-10-16,5,0.294495,2026-10-10,70.181676,494.759966
41,AAPL261016C00335000,2026-09-11 19:59:59+00:00,335.0,9.20,9.05,9.45,1.950000,26.896550,4757.0,11135,0.264900,False,REGULAR,USD,2026-10-16,5,0.289856,2026-10-10,65.184429,608.526400
42,AAPL261016C00340000,2026-09-11 19:59:49+00:00,340.0,6.99,6.90,7.10,1.470000,26.630432,9324.0,106553,0.256965,False,REGULAR,USD,2026-10-16,5,0.285461,2026-10-10,60.187183,761.046961
43,AAPL261016C00345000,2026-09-11 19:59:18+00:00,345.0,5.19,5.15,5.25,1.140000,28.148144,6043.0,25115,0.252266,False,REGULAR,USD,2026-10-16,5,0.282043,2026-10-10,55.189943,963.390031
44,AAPL261016C00350000,2026-09-11 19:59:32+00:00,350.0,3.76,3.65,3.85,0.810000,27.457624,9551.0,17621,0.250435,False,REGULAR,USD,2026-10-16,5,0.279175,2026-10-10,50.192742,1234.913340
45,AAPL261016C00355000,2026-09-11 19:58:22+00:00,355.0,2.78,2.63,2.79,0.680000,32.380955,2203.0,7952,0.249885,False,REGULAR,USD,2026-10-16,5,0.281677,2026-10-10,45.195857,1525.750260
46,AAPL261016C00360000,2026-09-11 19:59:31+00:00,360.0,1.92,1.85,1.98,0.420000,27.999996,10249.0,121770,0.249397,False,REGULAR,USD,2026-10-16,5,0.279053,2026-10-10,40.200149,1993.757744
47,AAPL261016C00365000,2026-09-11 19:59:50+00:00,365.0,1.32,1.29,1.36,0.290000,28.155348,1531.0,5866,0.248115,False,REGULAR,USD,2026-10-16,5,0.278381,2026-10-10,35.209585,2567.392816
48,AAPL261016C00370000,2026-09-11 19:56:48+00:00,370.0,0.94,0.89,0.95,0.190000,25.333332,2153.0,8533,0.249397,False,REGULAR,USD,2026-10-16,5,0.281616,2026-10-10,30.240097,3117.031619
49,AAPL261016C00375000,2026-09-11 19:54:34+00:00,375.0,0.66,0.61,0.66,0.140000,26.923088,1309.0,2192,0.250984,False,REGULAR,USD,2026-10-16,5,0.284424,2026-10-10,25.329713,3737.835337

In [208]:
df_put_future.head(50)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency,exp,remainingTradeDate,calculated_iv,futureDate,future_option_price,price_return
0,AAPL261016P00130000,2026-08-11 13:49:18+00:00,130.0,0.02,0.00,0.52,0.000000,0.000000,46.0,66,1.309574,False,REGULAR,USD,2026-10-16,5,0.849854,2026-10-10,1.223359e-29,-100.000000
1,AAPL261016P00135000,2026-07-16 17:24:05+00:00,135.0,0.05,0.00,1.01,0.000000,0.000000,2.0,70,1.377933,False,REGULAR,USD,2026-10-16,5,0.757507,2026-10-10,1.269589e-34,-100.000000
2,AAPL261016P00140000,2026-09-09 15:36:41+00:00,140.0,0.01,0.00,0.06,0.000000,0.000000,10.0,618,0.964844,False,REGULAR,USD,2026-10-16,5,0.971680,2026-10-10,3.640207e-20,-100.000000
3,AAPL261016P00145000,2026-09-08 16:53:46+00:00,145.0,0.03,0.00,0.04,0.000000,0.000000,3.0,395,0.898439,False,REGULAR,USD,2026-10-16,5,1.005615,2026-10-10,1.014384e-17,-100.000000
4,AAPL261016P00150000,2026-09-04 15:43:40+00:00,150.0,0.02,0.00,0.05,0.000000,0.000000,30.0,400,0.875001,False,REGULAR,USD,2026-10-16,5,0.917419,2026-10-10,8.794527e-20,-100.000000
5,AAPL261016P00155000,2026-09-09 15:22:45+00:00,155.0,0.01,0.00,0.01,0.000000,0.000000,28.0,170,0.750003,False,REGULAR,USD,2026-10-16,5,0.862305,2026-10-10,7.198527e-21,-100.000000
6,AAPL261016P00160000,2026-09-11 14:54:36+00:00,160.0,0.01,0.00,0.01,0.000000,0.000000,2.0,260,0.718753,False,REGULAR,USD,2026-10-16,5,0.859253,2026-10-10,1.055115e-19,-100.000000
7,AAPL261016P00165000,2026-09-08 16:43:49+00:00,165.0,0.15,0.00,0.52,0.000000,0.000000,1.0,230,0.998047,False,REGULAR,USD,2026-10-16,5,1.011780,2026-10-10,1.431499e-13,-100.000000
8,AAPL261016P00170000,2026-09-03 13:47:12+00:00,170.0,0.09,0.00,0.03,0.000000,0.000000,2.0,308,0.710940,False,REGULAR,USD,2026-10-16,5,0.887512,2026-10-10,2.685602e-16,-100.000000
9,AAPL261016P00175000,2026-09-08 14:35:20+00:00,175.0,0.02,0.00,0.08,0.000000,0.000000,2.0,623,0.746096,False,REGULAR,USD,2026-10-16,5,0.761353,2026-10-10,2.038413e-20,-100.000000
10,AAPL261016P00180000,2026-09-08 14:35:20+00:00,180.0,0.03,0.00,0.08,0.000000,0.000000,2.0,429,0.714847,False,REGULAR,USD,2026-10-16,5,0.756836,2026-10-10,2.403086e-19,-100.000000
11,AAPL261016P00185000,2026-09-04 17:47:15+00:00,185.0,0.02,0.00,0.44,0.000000,0.000000,14.0,872,0.830080,False,REGULAR,USD,2026-10-16,5,0.687561,2026-10-10,9.926807e-22,-100.000000
12,AAPL261016P00190000,2026-09-09 15:24:49+00:00,190.0,0.04,0.00,0.17,0.000000,0.000000,5.0,1614,0.710940,False,REGULAR,USD,2026-10-16,5,0.726135,2026-10-10,2.413462e-18,-100.000000
13,AAPL261016P00195000,2026-09-10 13:44:35+00:00,195.0,0.13,0.00,0.10,0.000000,0.000000,1.0,342,0.642582,False,REGULAR,USD,2026-10-16,5,0.802734,2026-10-10,3.257131e-14,-100.000000
14,AAPL261016P00200000,2026-09-11 17:41:23+00:00,200.0,0.02,0.00,0.05,0.010000,100.000000,4.0,1147,0.574223,False,REGULAR,USD,2026-10-16,5,0.646057,2026-10-10,5.186236e-20,-100.000000
15,AAPL261016P00205000,2026-09-11 16:09:02+00:00,205.0,0.05,0.02,0.24,0.000000,0.000000,7.0,1855,0.652347,False,REGULAR,USD,2026-10-16,5,0.672913,2026-10-10,2.570141e-17,-100.000000
16,AAPL261016P00210000,2026-09-11 16:50:49+00:00,210.0,0.05,0.02,0.10,-0.020000,-28.571426,6.0,3203,0.570317,False,REGULAR,USD,2026-10-16,5,0.641968,2026-10-10,1.140277e-17,-100.000000
17,AAPL261016P00215000,2026-09-11 19:54:17+00:00,215.0,0.04,0.00,0.16,-0.020000,-33.333336,78.0,3283,0.560551,False,REGULAR,USD,2026-10-16,5,0.598022,2026-10-10,7.697232e-19,-100.000000
18,AAPL261016P00220000,2026-09-11 16:53:36+00:00,220.0,0.05,0.03,0.07,-0.030000,-37.499996,106.0,3300,0.507817,False,REGULAR,USD,2026-10-16,5,0.582031,2026-10-10,1.767208e-18,-100.000000
19,AAPL261016P00225000,2026-09-11 18:49:49+00:00,225.0,0.06,0.05,0.06,-0.020000,-25.000000,48.0,2025,0.492193,False,REGULAR,USD,2026-10-16,5,0.563782,2026-10-10,2.867851e-18,-100.000000
20,AAPL261016P00230000,2026-09-11 19:28:23+00:00,230.0,0.06,0.04,0.10,-0.020000,-25.000000,21.0,4296,0.494146,False,REGULAR,USD,2026-10-16,5,0.534790,2026-10-10,9.164331e-19,-100.000000
21,AAPL261016P00235000,2026-09-11 18:31:59+00:00,235.0,0.09,0.06,0.12,-0.030000,-24.999996,27.0,6538,0.478521,False,REGULAR,USD,2026-10-16,5,0.530212,2026-10-10,1.026736e-17,-100.000000
22,AAPL261016P00240000,2026-09-11 19:51:14+00:00,240.0,0.09,0.06,0.13,-0.040000,-30.769226,31.0,6518,0.457037,False,REGULAR,USD,2026-10-16,5,0.501160,2026-10-10,2.871768e-18,-100.000000
23,AAPL261016P00245000,2026-09-11 18:51:20+00:00,245.0,0.12,0.07,0.13,-0.040000,-25.000000,23.0,4903,0.430670,False,REGULAR,USD,2026-10-16,5,0.489563,2026-10-10,1.103545e-17,-100.000000
24,AAPL261016P00250000,2026-09-11 19:38:24+00:00,250.0,0.15,0.11,0.15,-0.060000,-28.571424,653.0,5553,0.413092,False,REGULAR,USD,2026-10-16,5,0.474182,2026-10-10,2.295212e-17,-100.000000
25,AAPL261016P00255000,2026-09-11 19:37:47+00:00,255.0,0.17,0.12,0.20,-0.080000,-32.000000,259.0,5408,0.402838,False,REGULAR,USD,2026-10-16,5,0.452576,2026-10-10,1.689394e-17,-100.000000
26,AAPL261016P00260000,2026-09-11 19:37:47+00:00,260.0,0.21,0.20,0.24,-0.110000,-34.375000,434.0,6187,0.387213,False,REGULAR,USD,2026-10-16,5,0.436340,2026-10-10,2.861111e-17,-100.000000
27,AAPL261016P00265000,2026-09-11 19:45:32+00:00,265.0,0.24,0.21,0.29,-0.160000,-40.000004,340.0,3135,0.371588,False,REGULAR,USD,2026-10-16,5,0.415039,2026-10-10,1.917884e-17,-100.000000
28,AAPL261016P00270000,2026-09-11 19:59:00+00:00,270.0,0.29,0.30,0.33,-0.190000,-39.583336,500.0,8689,0.352546,False,REGULAR,USD,2026-10-16,5,0.397034,2026-10-10,2.153897e-17,-100.000000
29,AAPL261016P00275000,2026-09-11 19:44:54+00:00,275.0,0.38,0.38,0.42,-0.210000,-35.593216,353.0,5171,0.339850,False,REGULAR,USD,2026-10-16,5,0.384094,2026-10-10,6.075387e-17,-100.000000
30,AAPL261016P00280000,2026-09-11 19:54:59+00:00,280.0,0.48,0.46,0.51,-0.280000,-36.842106,1178.0,14716,0.323981,False,REGULAR,USD,2026-10-16,5,0.368713,2026-10-10,1.064145e-16,-100.000000
31,AAPL261016P00285000,2026-09-11 19:53:10+00:00,285.0,0.60,0.58,0.62,-0.340000,-36.170210,1825.0,8223,0.307868,False,REGULAR,USD,2026-10-16,5,0.352295,2026-10-10,1.483708e-16,-100.000000
32,AAPL261016P00290000,2026-09-11 19:59:40+00:00,290.0,0.78,0.76,0.85,-0.480000,-38.095238,2461.0,10838,0.299323,False,REGULAR,USD,2026-10-16,5,0.338440,2026-10-10,3.392089e-16,-100.000000
33,AAPL261016P00295000,2026-09-11 19:54:53+00:00,295.0,1.01,0.98,1.05,-0.630000,-38.414635,1851.0,10465,0.283577,False,REGULAR,USD,2026-10-16,5,0.324158,2026-10-10,7.062469e-16,-100.000000
34,AAPL261016P00300000,2026-09-11 19:59:36+00:00,300.0,1.38,1.34,1.39,-0.790000,-36.405533,3322.0,24425,0.272590,False,REGULAR,USD,2026-10-16,5,0.314270,2026-10-10,3.661872e-15,-100.000000
35,AAPL261016P00305000,2026-09-11 19:59:53+00:00,305.0,1.85,1.80,1.90,-1.120000,-37.710438,2394.0,10396,0.264351,False,REGULAR,USD,2026-10-16,5,0.303101,2026-10-10,1.467876e-14,-100.000000
36,AAPL261016P00310000,2026-09-11 19:59:52+00:00,310.0,2.55,2.50,2.63,-1.450000,-36.250000,6296.0,9055,0.258186,False,REGULAR,USD,2026-10-16,5,0.295532,2026-10-10,1.214344e-13,-100.000000
37,AAPL261016P00315000,2026-09-11 19:59:31+00:00,315.0,3.50,3.40,3.55,-1.900000,-35.185184,1575.0,7212,0.250740,False,REGULAR,USD,2026-10-16,5,0.289062,2026-10-10,1.200671e-12,-100.000000
38,AAPL261016P00320000,2026-09-11 19:59:59+00:00,320.0,4.70,4.70,4.80,-2.200000,-31.884062,3940.0,10793,0.245125,False,REGULAR,USD,2026-10-16,5,0.281738,2026-10-10,9.776543e-12,-100.000000
39,AAPL261016P00325000,2026-09-11 19:59:41+00:00,325.0,6.25,6.25,6.45,-2.750000,-30.555555,1357.0,2508,0.241341,False,REGULAR,USD,2026-10-16,5,0.275391,2026-10-10,9.063878e-11,-100.000000
40,AAPL261016P00330000,2026-09-11 19:59:42+00:00,330.0,8.30,8.15,8.40,-3.250000,-28.138527,4664.0,2944,0.235512,False,REGULAR,USD,2026-10-16,5,0.272766,2026-10-10,1.380659e-09,-100.000000
41,AAPL261016P00335000,2026-09-11 19:59:33+00:00,335.0,10.75,10.55,10.85,-3.690000,-25.554012,1796.0,1189,0.232033,True,REGULAR,USD,2026-10-16,5,0.269958,2026-10-10,1.749410e-08,-100.000000
42,AAPL261016P00340000,2026-09-11 19:57:05+00:00,340.0,13.34,13.15,13.70,-5.209999,-28.086250,2653.0,731,0.228066,True,REGULAR,USD,2026-10-16,5,0.259277,2026-10-10,7.552376e-08,-99.999999
43,AAPL261016P00345000,2026-09-11 18:20:03+00:00,345.0,16.55,16.35,16.95,-6.100000,-26.931568,144.0,579,0.223763,True,REGULAR,USD,2026-10-16,5,0.254272,2026-10-10,6.270764e-07,-99.999996
44,AAPL261016P00350000,2026-09-11 19:59:57+00:00,350.0,20.50,19.70,21.50,-4.879999,-19.227736,132.0,1352,0.248115,True,REGULAR,USD,2026-10-16,5,0.261841,2026-10-10,1.455323e-05,-99.999929
45,AAPL261016P00355000,2026-09-11 19:56:47+00:00,355.0,24.10,23.75,24.65,-9.100000,-27.409640,2.0,42,0.217964,True,REGULAR,USD,2026-10-16,5,0.243713,2026-10-10,3.059068e-05,-99.999873
46,AAPL261016P00360000,2026-09-11 19:03:55+00:00,360.0,28.40,27.70,29.00,-9.800001,-25.654453,15.0,44,0.217781,True,REGULAR,USD,2026-10-16,5,0.240784,2026-10-10,2.172290e-04,-99.999235
47,AAPL261016P00365000,2026-09-11 15:13:39+00:00,365.0,30.33,32.25,33.55,-33.670000,-52.609370,1.0,0,0.217781,True,REGULAR,USD,2026-10-16,5,0.000000,2026-10-10,0.000000e+00,-100.000000
48,AAPL261016P00370000,2026-09-10 16:00:31+00:00,370.0,50.60,36.85,38.30,0.000000,0.000000,1.0,1,0.222420,True,REGULAR,USD,2026-10-16,5,0.742554,2026-10-10,3.334278e+00,-93.410519
49,AAPL261016P00380000,2026-07-30 14:10:28+00:00,380.0,48.75,58.40,61.40,0.000000,0.000000,1.0,0,0.699527,True,REGULAR,USD,2026-10-16,5,0.279419,2026-10-10,3.066693e-01,-99.370935